# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/laurentletourneau-guillon/Dropbox/CHUM/RECHERCHE/1 PROJECTS/2023 BRATS/BraTS Slicer GUI/BraTS_GUI/BraTS_annotation/Resources/UI/BraTS_annotation.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BraTS_annotation(object):
    def setupUi(self, BraTS_annotation):
        BraTS_annotation.setObjectName("BraTS_annotation")
        BraTS_annotation.resize(749, 844)
        self.verticalLayout = QtWidgets.QVBoxLayout(BraTS_annotation)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inputsCollapsibleButton = ctkCollapsibleButton(BraTS_annotation)
        self.inputsCollapsibleButton.setObjectName("inputsCollapsibleButton")
        self.formLayout_2 = QtWidgets.QFormLayout(self.inputsCollapsibleButton)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.inputsCollapsibleButton)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.pushButton_DefaultDir = QtWidgets.QPushButton(self.inputsCollapsibleButton)
        self.pushButton_DefaultDir.setObjectName("pushButton_DefaultDir")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushButton_DefaultDir)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.listWidget = QtWidgets.QListWidget(self.inputsCollapsibleButton)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_4.addWidget(self.listWidget)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Previous = QtWidgets.QPushButton(self.inputsCollapsibleButton)
        self.pushButton_Previous.setObjectName("pushButton_Previous")
        self.horizontalLayout.addWidget(self.pushButton_Previous)
        self.pushButton_Next = QtWidgets.QPushButton(self.inputsCollapsibleButton)
        self.pushButton_Next.setObjectName("pushButton_Next")
        self.horizontalLayout.addWidget(self.pushButton_Next)
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.pushButton_Save = QtWidgets.QPushButton(self.inputsCollapsibleButton)
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pushButton_Save)
        self.verticalLayout.addWidget(self.inputsCollapsibleButton)
        self.outputsCollapsibleButton = ctkCollapsibleButton(BraTS_annotation)
        self.outputsCollapsibleButton.setObjectName("outputsCollapsibleButton")
        self.formLayout_4 = QtWidgets.QFormLayout(self.outputsCollapsibleButton)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_2 = QtWidgets.QLabel(self.outputsCollapsibleButton)
        self.label_2.setObjectName("label_2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.pushButton_OutDir = QtWidgets.QPushButton(self.outputsCollapsibleButton)
        self.pushButton_OutDir.setObjectName("pushButton_OutDir")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushButton_OutDir)
        self.verticalLayout.addWidget(self.outputsCollapsibleButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(BraTS_annotation)
        QtCore.QMetaObject.connectSlotsByName(BraTS_annotation)

    def retranslateUi(self, BraTS_annotation):
        _translate = QtCore.QCoreApplication.translate
        self.inputsCollapsibleButton.setText(_translate("BraTS_annotation", "Input"))
        self.label.setText(_translate("BraTS_annotation", "Default directory"))
        self.pushButton_DefaultDir.setText(_translate("BraTS_annotation", "Get default directory - Load cases"))
        self.pushButton_Previous.setText(_translate("BraTS_annotation", "Previous"))
        self.pushButton_Next.setText(_translate("BraTS_annotation", "Next"))
        self.pushButton_Save.setText(_translate("BraTS_annotation", "Save"))
        self.outputsCollapsibleButton.setText(_translate("BraTS_annotation", "Output"))
        self.label_2.setText(_translate("BraTS_annotation", "Output directory"))
        self.pushButton_OutDir.setText(_translate("BraTS_annotation", "Output directory"))
from ctkCollapsibleButton import ctkCollapsibleButton
from qMRMLWidget import qMRMLWidget
